# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('language_1', models.CharField(max_length=2)),
                ('language_2', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Sentences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence1', models.CharField(max_length=4000)),
                ('sentence2', models.CharField(max_length=4000)),
                ('order', models.IntegerField()),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reader.Composition')),
            ],
        ),
    ]
