# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_auto_20170208_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentences',
            name='part1',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part1', to='reader.Parts'),
        ),
        migrations.AlterField(
            model_name='sentences',
            name='part2',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part2', to='reader.Parts'),
        ),
    ]
