export const ACTION_SELECT_SENTENCE = 'ACTION_SELECT_SENTENCE';
export const ACTION_JOIN_SENTENCES = 'ACTION_JOIN_SENTENCES';
export const ACTION_UPDATE_SENTENCES = 'ACTION_UPDATE_SENTENCES';
export const ACTION_DEFAULT_STATE = 'ACTION_DEFAULT_STATE';
export const ACTION_UPDATE_LANGUAGES = 'ACTION_UPDATE_LANGUAGES';